// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";
import type { FileInAlbum } from "./FileInAlbum";

export interface AlbumWithFiles { album: Album, files_in_album: Array<FileInAlbum>, }