// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Album { id: number, pub_id: string, name: string, date_created: string, date_modified: string, }