// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";
import type { File } from "./File";

export interface FileInAlbum { album_id: number, album: Album | null, file_id: number, file: File | null, date_created: string, }